services:
  - type: web
    name: vivek-ramanan
    runtime: static
    buildCommand: ""
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /images/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
